[package]
name = "bevy_simple_tilemap"
version = "0.5.1"
authors = ["Forb.Jok <forbjok@gmail.com>"]
edition = "2021"
description = "Refreshingly simple tilemap implementation for Bevy Engine."
license = "MIT/Apache-2.0"
repository = "https://github.com/forbjok/bevy_simple_tilemap.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", branch = "main" }
bevy_derive = { git = "https://github.com/bevyengine/bevy.git", branch = "main" }
bitflags = "1.3.2"
bytemuck = "1.7.2"
crevice = { git = "https://github.com/bevyengine/bevy.git", branch = "main" }
wgpu = "0.12.0"

[[example]]
name = "benchmark"
path = "examples/benchmark.rs"

[[example]]
name = "multilayer"
path = "examples/multilayer.rs"

[[example]]
name = "simple"
path = "examples/simple.rs"
